// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwwyrbaqypltnsclcaqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3d3lyYmFxeXBsdG5zY2xjYXFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTQ2MDksImV4cCI6MjA3MTMzMDYwOX0.ipuLJhr9wW8ioATW9LxnvgtZzMIJ8HM9TEOJuPIUJ0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});